# Generated by Django 5.0 on 2023-12-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_pages_created_at_pages_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
